version: '3'

services:
    reverseproxy:
        build:
	   context: ./proxy4scholia
	   dockerfile: Dockerfile
        #image: proxy:latest
        ports:
            - 8080:8080
        restart: always

    scholiawithproxy:
        build:
	   context: ./scholiawithproxy
	   dockerfile: Dockerfile
        #image: scholia:latest
        ports:
            - 8100
        restart: always
